### ISSUE TITLE
Java exception when running large number of simulations

### ISSUE THREAD

**Issue by lutzilutz** [lutzilutz/TraficCERN#40]
To fix quickly !

**Comment by lutzilutz** [comment]
Index out of bound (-1) in
Network.java at line 1644

**Comment by lutzilutz** [comment]
Full stack trace :

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at network.Network.selectRidesWithProbability(Network.java:1645)
	at network.NetworkComputing.computeEvolution(NetworkComputing.java:459)
	at states.SimState.tick(SimState.java:327)
	at main.Simulation.tick(Simulation.java:88)
	at main.Simulation.run(Simulation.java:137)
	at java.lang.Thread.run(Unknown Source)
