### ISSUE TITLE
Java exception during simulation (empty ride + no probability found for a road)

### ISSUE THREAD

**Issue by lutzilutz** [lutzilutz/TraficCERN#43]
Between 9am and 10am, a java exception occurs where a vehicle has an empty ride. It seems that this error is generated by a road with a null or missing probability. As Pavlos suggested, this could be caused by the algorithm computing the probability of vehicles being generated (maybe a very small probability that should be instead null). I'll copy/paste the error just below for further inspection.

Concerned roads so far : C5SW and SortieCERNSE

Concerned hours : 9am to 10am

This occurs randomly after some simulations.

**Comment by lutzilutz** [comment]
Error example, happened at simulation n°4, at 19:58:33
**Our error output**
ERROR : No adapted probability found for rSortieCERNNW :
0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 [11.0, 11.0, 11.0, 22.0, 22.0, 110.0, 165.0, 738.1, 685.3, 509.3, 165.0, 165.0, 165.0, 165.0, 165.0, 165.0, 165.0, 126.5, 239.8, 218.9, 220.0, 220.0, 220.0, 220.0]
ERROR : Vehicle with empty ride
**Java stacktrace**
Exception in thread "Thread-0" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at network.NetworkComputing.computeEvolution(NetworkComputing.java:492)
	at states.SimState.tick(SimState.java:328)
	at main.Simulation.tick(Simulation.java:91)
	at main.Simulation.run(Simulation.java:140)
	at java.lang.Thread.run(Thread.java:748)

**Comment by lutzilutz** [comment]
Additionnal informations :

It looks like the road has a non-zero flow, but the chosen ride is null and then the vehicle gets an empty ride.

**Comment by lutzilutz** [comment]
Possible explanation :

The probability matrix have a value small enough that it is register as 0 when saving it into a `float` field.
